services:
  chrome:
    build:
      context: ./chrome/
    platform: linux/amd64
    mem_limit: 2g
    volumes:
      - ./chrome-profile:/home/chromeuser/profile
    environment:
      PORT: 3003
      CHROME_CONTROL_PORT: 9223
      CHROME_CONTROL_COOLDOWN_MS: 5000
      ENABLE_GUI_CONTROL: "true"
      XPRA_PORT: 14500
      CHROME_SCREEN_WIDTH: 1920
      CHROME_SCREEN_HEIGHT: 1080
    dns:
      - 8.8.8.8
      - 1.1.1.1
    ports:
      - 127.0.0.1:14500:14500
  thermoptic:
    build: .
    volumes:
      - ./ssl:/work/cassl
      - ./hooks:/work/hooks
    depends_on:
      - chrome
    ports:
      - 127.0.0.1:1234:1234
    environment:
      # The thermoptic HTTP proxy port that
      # is exposed for your HTTP clients to use.
      HTTP_PROXY_PORT: 1234
      # The port that CDP is listening on
      # for thermoptic to connect to
      CHROME_DEBUGGING_PORT: 3003
      # This is the hostname that thermoptic
      # will use to contact chrome
      CHROME_DEBUGGING_HOST: chrome
      CHROME_CONTROL_PORT: 9223
      THERMOPTIC_CONTAINER_RUNTIME: "true"
      # The username for thermoptic HTTP proxy
      PROXY_USERNAME: changeme
      # The password for thermoptic HTTP proxy
      PROXY_PASSWORD: changeme
      # If you're encountering a bug then set this to true
      # before you file an issue. It will help me debug your
      # problem as verbose statements are printed.
      DEBUG: false
      # Hook that runs on proxy start
      # ON_START_HOOK_FILE_PATH: /work/hooks/onstart.js
      # Hook that runs before each HTTP request
      # is proxied through thermoptic
      # BEFORE_REQUEST_HOOK_FILE_PATH: /work/hooks/beforerequest.js
      # Hook that runs after each HTTP request
      # is proxied through thermoptic.
      # AFTER_REQUEST_HOOK_FILE_PATH: /work/hooks/afterrequest.js
      HEALTHCHECK_ENDPOINT_PORT: 8085
      HEALTHCHECK_ENDPOINT_PATH: /__thermoptic_health
      ENABLE_GUI_CONTROL: "true"
      CHROME_SCREEN_WIDTH: 1920
      CHROME_SCREEN_HEIGHT: 1080
